# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 0a135b0dacae4b77a470a63d8393f31a170913278b693d99ff461dcfa5560397a5b84876bf7ce9b7d9eff8835167324ad3e7a9fd1b4186f8c1cb08aa9463233c

test:
  secret_key_base: 31808185e7ac59537c3087792a70fd14311e4b3b811acd627ab455b21205c45ec203ef809e28dc902c12e517d586ca123af781984a19f342e4a7b01ea9047213

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
